Add sqlite database
openkfw/qupo pull request #10
Opened 2022-05-09 10:14 UTC by melissaSchmidt0302

- [ ] Add schema and sqlite database to api
- [ ] Endpoint to create a database entry if entry cannot be found

Closes #1

2022-05-10 06:19 UTC, melissaSchmidt0302 commented on api/app/db/database.py
> +DATABASE_URL = "sqlite:///./app/db/finance.db"
for sure that might be a good idea. The next step would be to replace it by a centrally stored file like azure blob storage.

2022-05-17 09:12 UTC, melissaSchmidt0302 commented on api/app/tickers/operations.py
> +    data = yfinance.Ticker(stock.symbol)
@leonox

2022-05-17 14:17 UTC, mathiashoeld requested changes

2022-05-17 14:17 UTC, mathiashoeld commented on api/app/main.py
> +    return {"message": "Hello from qupo"}
please be aware to use flake8-quotes for the correct use of quote signs

2022-05-17 14:17 UTC, mathiashoeld commented on api/app/tickers/tickers.py
> +@router.post("/stock/", response_model=schemas.Stock)
this is a little confusing - the function name is `getStock`, but the endpoint is a `POST` endpoint

2022-05-23 09:40 UTC, merged